import { FormEvent, useEffect, useState } from 'react'
import { ArrowUpRight, BarChart3, Check, FileText, LayoutDashboard, LogIn, LogOut, Sparkles, Target, Upload, Video, X } from 'lucide-react'
import InterviewRoom from './InterviewRoom'
import { Analysis, analyzeResume, listAnalyses, login, me, register, User } from './api'

type View = 'landing' | 'login' | 'register' | 'dashboard' | 'analyze' | 'skills' | 'roadmap' | 'interview'
const nav = [{ id: 'dashboard', label: 'Dashboard', icon: LayoutDashboard }, { id: 'analyze', label: 'New analysis', icon: FileText }, { id: 'skills', label: 'Evidence map', icon: Target }, { id: 'roadmap', label: 'Learning path', icon: BarChart3 }, { id: 'interview', label: 'AI interview', icon: Video }] as const

export default function App() {
  const [user, setUser] = useState<User | null>(null)
  const [view, setView] = useState<View>('landing')
  const [analysis, setAnalysis] = useState<Analysis | null>(null)
  const [analyses, setAnalyses] = useState<Analysis[]>([])
  const [loading, setLoading] = useState(true)

  useEffect(() => { if (localStorage.getItem('skillsync_token')) me().then((current) => { setUser(current); setView('dashboard'); return listAnalyses() }).then(setAnalyses).catch(() => localStorage.removeItem('skillsync_token')).finally(() => setLoading(false)); else setLoading(false) }, [])
  const authenticated = (next: View) => { if (user) setView(next); else setView('login') }
  const onAuth = (result: { access_token: string; user: User }) => { localStorage.setItem('skillsync_token', result.access_token); setUser(result.user); setView('dashboard'); listAnalyses().then(setAnalyses).catch(() => undefined) }
  const logout = () => { localStorage.removeItem('skillsync_token'); setUser(null); setAnalysis(null); setView('landing') }
  if (loading) return <div className="auth-loading">Loading your workspace...</div>
  if (!user && (view === 'login' || view === 'register')) return <Auth mode={view} onAuth={onAuth} onSwitch={() => setView(view === 'login' ? 'register' : 'login')} />
  if (!user) return <Landing onLogin={() => setView('login')} onRegister={() => setView('register')} />
  return <div className="app-shell"><aside className="sidebar"><div className="brand"><div className="brand-mark"><Sparkles size={18} /></div><span>SkillSync <em>AI</em></span></div><div className="workspace-label">WORKSPACE</div><nav>{nav.map(({ id, label, icon: Icon }) => <button key={id} className={view === id ? 'nav-item active' : 'nav-item'} onClick={() => authenticated(id)}><Icon size={17} /><span>{label}</span></button>)}</nav><div className="sidebar-bottom"><button className="profile"><div className="avatar">{user.name.slice(0, 2).toUpperCase()}</div><span><strong>{user.name}</strong><small>{user.email}</small></span></button><button className="logout-button" onClick={logout}><LogOut size={14} /> Log out</button></div></aside><main className="main-content"><header className="topbar"><div><span className="eyebrow">CAREER INTELLIGENCE</span><h1>{view === 'dashboard' ? `Welcome, ${user.name}` : nav.find((item) => item.id === view)?.label}</h1></div><div className="privacy"><span className="status-dot" /> Private workspace</div></header>{view === 'dashboard' && <Dashboard user={user} analyses={analyses} onNew={() => setView('analyze')} onOpen={(item) => { setAnalysis(item); setView('skills') }} />}{view === 'analyze' && <Analyze onComplete={(item) => { setAnalysis(item); setAnalyses((items) => [item, ...items]); setView('skills') }} />}{view === 'skills' && (analysis ? <Skills analysis={analysis} onInterview={() => setView('interview')} /> : <Empty title="No analysis selected" text="Start a new analysis to see your evidence map." action={() => setView('analyze')} />)}{view === 'roadmap' && (analysis ? <Roadmap analysis={analysis} /> : <Empty title="No learning path yet" text="Complete an analysis to generate a personalized learning path." action={() => setView('analyze')} />)}{view === 'interview' && (analysis ? <InterviewRoom analysis={analysis} /> : <Empty title="No interview ready" text="Complete an analysis before starting an interview." action={() => setView('analyze')} />)}</main></div>
}

function Landing({ onLogin, onRegister }: { onLogin: () => void; onRegister: () => void }) { return <div className="public-page"><div className="public-nav"><div className="brand"><div className="brand-mark"><Sparkles size={18} /></div><span>SkillSync <em>AI</em></span></div><div><button className="text-button" onClick={onLogin}>Log in</button><button className="primary-button" onClick={onRegister}>Create account <ArrowUpRight size={15} /></button></div></div><section className="public-hero"><span className="pill"><span className="pulse" /> Career intelligence for your next move</span><h2>From resume<br /><span>to readiness.</span></h2><p>Analyze your own resume against the role you want, understand the evidence, and prepare with an AI interviewer.</p><button className="primary-button" onClick={onRegister}>Create your workspace <ArrowUpRight size={16} /></button><div className="workflow"><span>Analyze</span><i>→</i><span>Explain</span><i>→</i><span>Improve</span><i>→</i><span>Interview</span><i>→</i><span>Feedback</span></div></section></div> }

function Auth({ mode, onAuth, onSwitch }: { mode: 'login' | 'register'; onAuth: (result: { access_token: string; user: User }) => void; onSwitch: () => void }) { const [name, setName] = useState(''); const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [confirm, setConfirm] = useState(''); const [error, setError] = useState(''); const [busy, setBusy] = useState(false); const submit = async (event: FormEvent) => { event.preventDefault(); setError(''); if (mode === 'register' && password !== confirm) { setError('Passwords do not match.'); return } setBusy(true); try { onAuth(mode === 'register' ? await register(name, email, password) : await login(email, password)) } catch (caught) { setError(caught instanceof Error ? caught.message : 'Authentication failed.') } finally { setBusy(false) } }; return <div className="auth-page"><div className="auth-card"><div className="brand"><div className="brand-mark"><Sparkles size={18} /></div><span>SkillSync <em>AI</em></span></div><span className="eyebrow">{mode === 'register' ? 'CREATE YOUR WORKSPACE' : 'WELCOME BACK'}</span><h2>{mode === 'register' ? 'Start with your story.' : 'Return to your readiness.'}</h2><p>{mode === 'register' ? 'Your analyses and interview history stay connected to your account.' : 'Sign in to continue your private career workspace.'}</p><form onSubmit={submit}>{mode === 'register' && <input value={name} onChange={(event) => setName(event.target.value)} placeholder="Full name" required />}{<input type="email" value={email} onChange={(event) => setEmail(event.target.value)} placeholder="Email address" required />}{<input type="password" value={password} onChange={(event) => setPassword(event.target.value)} placeholder="Password (8+ characters)" minLength={8} required />}{mode === 'register' && <input type="password" value={confirm} onChange={(event) => setConfirm(event.target.value)} placeholder="Confirm password" required />}{error && <div className="error-message">{error}</div>}<button className="primary-button auth-submit" disabled={busy}>{busy ? 'Working...' : mode === 'register' ? 'Create account' : 'Log in'} <ArrowUpRight size={16} /></button></form><button className="text-button" onClick={onSwitch}>{mode === 'register' ? 'Already have an account? Log in' : 'New here? Create an account'}</button></div></div> }

function Dashboard({ user, analyses, onNew, onOpen }: { user: User; analyses: Analysis[]; onNew: () => void; onOpen: (analysis: Analysis) => void }) { return <div className="dashboard-page"><section className="dashboard-hero"><span className="pill"><span className="pulse" /> Private workspace</span><h2>Make your next move<br /><span>more intentional.</span></h2><p>Upload your resume and target job description to get a personalized readiness picture.</p><button className="primary-button" onClick={onNew}>New resume analysis <ArrowUpRight size={16} /></button></section><div className="section-heading"><div><span className="eyebrow">YOUR HISTORY</span><h3>Previous analyses</h3></div><button className="text-button" onClick={onNew}>+ New analysis</button></div>{analyses.length === 0 ? <Empty title="No analyses yet." text={`Upload your resume and target job description to get started, ${user.name}.`} action={onNew} /> : <div className="history-list">{analyses.map((item) => <button className="history-row" key={item.id} onClick={() => onOpen(item)}><FileText size={18} /><span><strong>{item.role}</strong><small>{item.created_at ? new Date(item.created_at).toLocaleDateString() : 'Recently created'}</small></span><b>{item.score}%</b><ArrowUpRight size={15} /></button>)}</div>}<div className="empty-interviews"><Video size={18} /><div><strong>No interviews completed yet.</strong><p>Complete an analysis to prepare for your first AI HR interview.</p></div></div></div> }

function Analyze({ onComplete }: { onComplete: (analysis: Analysis) => void }) { const [file, setFile] = useState<File | null>(null); const [job, setJob] = useState(''); const [error, setError] = useState(''); const [busy, setBusy] = useState(false); const submit = async () => { if (!file || !job.trim()) { setError('Upload a PDF or DOCX resume and paste a job description.'); return } setBusy(true); setError(''); try { onComplete(await analyzeResume(file, job)) } catch (caught) { setError(caught instanceof Error ? caught.message : 'We could not complete the analysis.') } finally { setBusy(false) } }; return <div className="form-page"><div className="form-intro"><span className="eyebrow">NEW ANALYSIS</span><h2>Bring your role into focus.</h2><p>Only the resume and job description you provide will be analyzed.</p></div><div className="input-grid"><label className="upload-zone"><input type="file" accept=".pdf,.docx" onChange={(event) => setFile(event.target.files?.[0] ?? null)} /><div className="upload-icon"><Upload size={20} /></div><strong>{file ? file.name : 'Upload your resume'}</strong><span>{file ? 'Ready to analyze' : 'PDF or DOCX · up to 10 MB'}</span></label><label className="jd-field"><span>TARGET JOB DESCRIPTION <small>Required</small></span><textarea value={job} onChange={(event) => setJob(event.target.value)} placeholder="Paste the job description here..." /><em>{job.length} characters</em></label></div>{error && <div className="error-message">{error}</div>}<div className="privacy-note"><span className="status-dot" /><span>Your resume and interview data are used only for your preparation.</span></div><button className="primary-button analyze-button" onClick={() => void submit()} disabled={busy}>{busy ? 'Analyzing your resume and job description...' : 'Analyze my resume'} <ArrowUpRight size={16} /></button></div> }

function Skills({ analysis, onInterview }: { analysis: Analysis; onInterview: () => void }) { return <div className="detail-page"><div className="detail-header"><div><span className="eyebrow">YOUR ANALYSIS / {analysis.role.toUpperCase()}</span><h2>The evidence behind your score.</h2><p>Every result below comes from your uploaded resume and supplied job description.</p></div><div className="score-mini"><strong>{analysis.score}%</strong><span>overall match</span></div></div><div className="metrics-grid"><div className="score-card"><div className="card-label">OVERALL MATCH</div><div className="score-row"><strong>{analysis.score}<small>%</small></strong></div></div><div className="breakdown-card">{analysis.scoreBreakdown.map((item) => <div className="breakdown-row" key={item.label}><span>{item.label}</span><div className="bar"><i style={{ width: `${item.value}%` }} /></div><strong>{item.value}</strong></div>)}</div><div className="next-card"><strong>Ready to practice?</strong><p>Your questions were generated from this analysis.</p><button onClick={onInterview}>Start interview <ArrowUpRight size={15} /></button></div></div><div className="evidence-list">{analysis.skills.map((skill) => <div className="evidence-row" key={skill.name}><div className={`evidence-status ${skill.status}`}>{skill.status === 'matched' ? <Check size={15} /> : skill.status === 'partial' ? '~' : '○'}</div><div className="evidence-skill"><strong>{skill.name}</strong><span>{skill.status === 'matched' ? 'Matched' : skill.status === 'partial' ? 'Partial match' : 'Not clearly demonstrated'}</span></div><div className="evidence-copy"><div><span>JOB DESCRIPTION</span><p>{skill.requirement}</p></div><div><span>YOUR RESUME</span><p>{skill.evidence}</p></div></div></div>)}</div></div> }

function Roadmap({ analysis }: { analysis: Analysis }) { return <div className="detail-page"><div className="detail-header"><div><span className="eyebrow">YOUR PERSONALIZED LEARNING PATH</span><h2>Improve what this role asks for.</h2><p>This roadmap is generated from the gaps in your current analysis.</p></div></div>{analysis.roadmap.length === 0 ? <Empty title="No major gaps identified." text="Your supplied resume clearly demonstrates the analyzed requirements." /> : <div className="roadmap-list">{analysis.roadmap.map((item, index) => <div className="roadmap-item" key={item.skill}><div className="roadmap-number">0{index + 1}</div><div><div className="roadmap-title"><h3>{item.skill}</h3></div><div className="roadmap-steps">{item.steps.map((step, stepIndex) => <div key={step}><span>{stepIndex + 1}</span>{step}</div>)}</div><div className="mini-project"><Sparkles size={15} /><span><b>Practice:</b> {item.project}</span></div></div></div>)}</div>}</div> }

function Empty({ title, text, action }: { title: string; text: string; action?: () => void }) { return <div className="empty-state"><FileText size={22} /><h3>{title}</h3><p>{text}</p>{action && <button className="primary-button" onClick={action}>Get started <ArrowUpRight size={15} /></button>}</div> }
